import '../models/evidence_item.dart';
import '../models/knowledge_delta.dart';
import '../models/note_draft.dart';

abstract class SummaryWriter {
  Future<NoteDraft> write({
    required String question,
    required List<EvidenceItem> localEvidence,
    required List<EvidenceItem> webEvidence,
    required List<KnowledgeDelta> deltas,
  });
}

NoteDraftAction chooseNoteDraftAction({
  required List<EvidenceItem> webEvidence,
  required List<KnowledgeDelta> deltas,
}) {
  if (webEvidence.isEmpty) return NoteDraftAction.doNotSave;
  if (deltas.isEmpty) return NoteDraftAction.doNotSave;

  final allDuplicates = deltas.every((d) => d.deltaType == DeltaType.duplicate);
  if (allDuplicates) return NoteDraftAction.doNotSave;

  final hasNewContent = deltas.any((d) =>
      d.deltaType == DeltaType.newClaim ||
      d.deltaType == DeltaType.relatedButNew);
  if (hasNewContent) return NoteDraftAction.createNewNote;

  final hasBetterSource =
      deltas.any((d) => d.deltaType == DeltaType.betterSource);
  if (hasBetterSource) return NoteDraftAction.appendToExistingNote;

  return NoteDraftAction.doNotSave;
}

class MockSummaryWriter implements SummaryWriter {
  @override
  Future<NoteDraft> write({
    required String question,
    required List<EvidenceItem> localEvidence,
    required List<EvidenceItem> webEvidence,
    required List<KnowledgeDelta> deltas,
  }) async {
    final action = chooseNoteDraftAction(
      webEvidence: webEvidence,
      deltas: deltas,
    );

    final markdown = action == NoteDraftAction.doNotSave
        ? _buildNoKnowledgeMarkdown(question)
        : _buildMarkdown(
            question: question,
            localEvidence: localEvidence,
            webEvidence: webEvidence,
            deltas: deltas,
          );

    return NoteDraft(
      question: question,
      markdownContent: markdown,
      action: action,
      deltas: deltas,
      localEvidence: localEvidence,
      webEvidence: webEvidence,
    );
  }

  // ---------------------------------------------------------------------------
  // Markdown builders
  // ---------------------------------------------------------------------------

  String _buildNoKnowledgeMarkdown(String question) {
    final buffer = StringBuffer();
    buffer.writeln('# No New Knowledge Found');
    buffer.writeln();
    buffer.writeln('**Question:** $question');
    buffer.writeln();
    buffer.writeln(
        'No durable new knowledge was found for this query. '
        'The incoming evidence was either empty, already covered by existing notes, '
        'or did not meet the threshold for a new insight.');
    buffer.writeln();
    buffer.writeln('---');
    buffer.writeln('_Draft generated by Grepink knowledge ingestion._');
    return buffer.toString();
  }

  String _buildMarkdown({
    required String question,
    required List<EvidenceItem> localEvidence,
    required List<EvidenceItem> webEvidence,
    required List<KnowledgeDelta> deltas,
  }) {
    final buffer = StringBuffer();

    buffer.writeln('# Note Draft');
    buffer.writeln();
    buffer.writeln('**Question:** $question');
    buffer.writeln();

    if (localEvidence.isNotEmpty) {
      buffer.writeln('## Related Notes');
      for (final item in localEvidence) {
        buffer.writeln('- **${item.title}**: ${_truncate(item.content, 120)}');
      }
      buffer.writeln();
    }

    if (webEvidence.isNotEmpty) {
      buffer.writeln('## Web Evidence');
      for (final item in webEvidence) {
        final source = item.sourceUrl != null
            ? ' ([source](${item.sourceUrl}))'
            : ' _(unsourced)_';
        buffer.writeln(
            '- **${item.title}**$source: ${_truncate(item.content, 120)}');
      }
      buffer.writeln();
    }

    if (deltas.isNotEmpty) {
      buffer.writeln('## Knowledge Deltas');
      for (final delta in deltas) {
        final label = delta.deltaType.name;
        buffer.writeln(
            '- **[$label]** ${_truncate(delta.evidence.content, 100)} — _${delta.reason}_');
      }
      buffer.writeln();
    }

    buffer.writeln('---');
    buffer.writeln('_Draft generated by Grepink knowledge ingestion._');

    return buffer.toString();
  }

  String _truncate(String text, int maxLength) {
    if (text.length <= maxLength) return text;
    return '${text.substring(0, maxLength)}…';
  }
}
