import '../models/evidence_item.dart';
import '../models/knowledge_delta.dart';
import '../models/note_draft.dart';

abstract class SummaryWriter {
  Future<NoteDraft> write({
    required String question,
    required List<EvidenceItem> localEvidence,
    required List<EvidenceItem> webEvidence,
    required List<KnowledgeDelta> deltas,
  });
}

class MockSummaryWriter implements SummaryWriter {
  @override
  Future<NoteDraft> write({
    required String question,
    required List<EvidenceItem> localEvidence,
    required List<EvidenceItem> webEvidence,
    required List<KnowledgeDelta> deltas,
  }) async {
    final allDuplicates =
        deltas.isNotEmpty && deltas.every((d) => d.deltaType == DeltaType.duplicate);

    final action =
        allDuplicates ? NoteDraftAction.doNotSave : NoteDraftAction.createNewNote;

    final markdown = _buildMarkdown(
      question: question,
      localEvidence: localEvidence,
      webEvidence: webEvidence,
      deltas: deltas,
    );

    return NoteDraft(
      question: question,
      markdownContent: markdown,
      action: action,
      deltas: deltas,
      localEvidence: localEvidence,
      webEvidence: webEvidence,
    );
  }

  String _buildMarkdown({
    required String question,
    required List<EvidenceItem> localEvidence,
    required List<EvidenceItem> webEvidence,
    required List<KnowledgeDelta> deltas,
  }) {
    final buffer = StringBuffer();

    buffer.writeln('# Note Draft');
    buffer.writeln();
    buffer.writeln('**Question:** $question');
    buffer.writeln();

    if (localEvidence.isNotEmpty) {
      buffer.writeln('## Related Notes');
      for (final item in localEvidence) {
        buffer.writeln('- **${item.title}**: ${_truncate(item.content, 120)}');
      }
      buffer.writeln();
    }

    if (webEvidence.isNotEmpty) {
      buffer.writeln('## Web Evidence');
      for (final item in webEvidence) {
        final source = item.sourceUrl != null ? ' ([source](${item.sourceUrl}))' : '';
        buffer.writeln('- **${item.title}**$source: ${_truncate(item.content, 120)}');
      }
      buffer.writeln();
    }

    if (deltas.isNotEmpty) {
      buffer.writeln('## Knowledge Deltas');
      for (final delta in deltas) {
        final label = delta.deltaType.name;
        buffer.writeln('- **[$label]** ${_truncate(delta.evidence.content, 100)} — _${delta.reason}_');
      }
      buffer.writeln();
    }

    buffer.writeln('---');
    buffer.writeln('_Draft generated by Grepink knowledge ingestion._');

    return buffer.toString();
  }

  String _truncate(String text, int maxLength) {
    if (text.length <= maxLength) return text;
    return '${text.substring(0, maxLength)}…';
  }
}
